name: Deploy Laravel to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.222.186.214 >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.222.186.214 << 'EOF'
            cd /var/www/laravel || exit 1
            if [ ! -d ".git" ]; then
              git clone https://github.com/awsradhe/liveserverconnect.git .
            else
              git pull origin main
            fi
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo chown -R www-data:www-data /var/www/laravel
            sudo chmod -R 775 /var/www/laravel/storage
            exit
          EOF
